name: CI

on:
  push:
    branches:
      - mejoras

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias del backend
        run: npm install

      - name: Instalar dependencias del frontend
        working-directory: frontend
        run: npm install

      - name: Compilar frontend
        working-directory: frontend
        env:
          CI: false
        run: npm run build

    # ver si anda el secret de github actions para mongodb
      - name: Levantar backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm start &

      - name: Levantar frontend
        working-directory: frontend
        run: npm start &

    # esperar que la aplicación inicie para asegurarse de que los tests de Cypress puedan ejecutarse correctamente
      - name: Esperar que la aplicación inicie
        run: sleep 10

    # ejecutar los tests de Cypress
      - name: Ejecutar Cypress
        run: npm run cypress:run

        # subir los screenshots de Cypress como artifact de GitHub Actions
      - name: Subir screenshots de Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
        

