name: CI

on:
  push:
    branches:
      - mejoras

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias del backend
        run: npm install

      - name: Instalar dependencias del frontend
        working-directory: frontend
        run: npm install

        

      